Repository VitaCheck/vitacheck-fe, pull requests merged in 2025-08, with the labels that each got.

#52 목적 api 연동중
  pnpm-lock.yaml
  public/images/PNG/Purpose2/allarrow.png
  public/images/PNG/Purpose2/background line.png
  public/images/PNG/Purpose2/눈건강_drop down.png
  public/images/PNG/Purpose2/오메가3_arrow.png
  src/App.tsx
  src/components/Purpose/PurposeRecommendedProductSection.tsx
  src/hooks/useIsMobile.ts
  src/pages/MainProductDetailPage.tsx
  src/pages/purpose/ObjectPage.tsx
  src/pages/purpose/PurposeIngredientProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: ✨ Feature

#51 feat: 자체 login ui, 연동
  public/images/cameraModal.png
  public/images/galleryModal.png
  public/images/ion_eye-1.png
  public/images/ion_eye.png
  src/App.tsx
  src/components/Footer.tsx
  src/pages/alarm/AlarmAddModal.tsx
  src/pages/alarm/AlarmEditModal.tsx
  src/pages/alarm/AlarmPage.tsx
  src/pages/alarm/DesktopAlarmAddPage.tsx
  src/pages/alarm/DesktopAlarmEditPage.tsx
  src/pages/alarm/DesktopAlarmPage.tsx
  src/pages/alarm/DesktopAlarmSettingsPage.tsx
  src/pages/auth/EmailLoginPage.tsx
  vite.config.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#59 fix: App.tsx conflict 해결
  src/App.tsx
Labels: 🐛 BugFix

#60 Feat/axios notification
  public/images/check-green.png
  public/images/check-white.png
  public/images/female.png
  public/images/male.png
  src/App.tsx
  src/pages/alarm/DesktopAlarmAddPage.tsx
  src/pages/alarm/DesktopAlarmEditPage.tsx
  src/pages/auth/EmailSignupDetailPAge.tsx
  src/pages/auth/EmailSignupPage.tsx
Labels: ✨ Feature, 📬 API

#63 목적 api 수정 중
  fetchApiData.mjs
  pnpm-lock.yaml
  public/images/PNG/MainPurpose/background line 1.png
  public/images/PNG/MainPurpose/clock.png
  public/images/PNG/MainPurpose/dotted line.png
  public/images/PNG/MainPurpose/heart.png
  public/images/PNG/MainPurpose/heart_line.png
  public/images/PNG/MainPurpose/kakaotalk.png
  public/images/PNG/MainPurpose/selection line 1.png
  public/images/PNG/MainPurpose/selection line 2.png
  public/images/PNG/MainPurpose/더보기 arrow.png
  public/images/PNG/MainPurpose/더보기.png
  public/images/PNG/MainPurpose/상세정보.png
  public/images/PNG/MainPurpose/쿠팡 바로가기.png
  public/images/VitaCheckPurpose/purpose10.png
  public/images/VitaCheckPurpose/purpose11.png
  public/images/VitaCheckPurpose/purpose12.png
  public/images/VitaCheckPurpose/purpose13.png
  public/images/VitaCheckPurpose/purpose14.png
  public/images/VitaCheckPurpose/purpose15.png
  public/images/VitaCheckPurpose/purpose16.png
  public/images/VitaCheckPurpose/purpose17.png
  public/images/VitaCheckPurpose/purpose19.png
  public/images/VitaCheckPurpose/purpose20.png
  public/images/VitaCheckPurpose/purpose21.png
  public/images/VitaCheckPurpose/purpose22.png
  public/images/VitaCheckPurpose/purpose25.png
  public/images/VitaCheckPurpose/purpose27.png
  public/images/VitaCheckPurpose/purpose28.png
  public/images/VitaCheckPurpose/purpose3.png
  public/images/VitaCheckPurpose/purpose6.png
  public/images/VitaCheckPurpose/purpose7.png
  public/images/VitaCheckPurpose/purpose9.png
  src/components/Purpose/DesktopMainDetailPage.tsx
  src/components/Purpose/DesktopPurpose2Section.tsx
  src/components/Purpose/IngredientTab.tsx
  src/components/Purpose/MainDetailPageBrandSection.tsx
  src/components/Purpose/MobileMainDetailPage.tsx
  src/components/Purpose/MobilePurpose2Section.tsx
  src/components/Purpose/Purpose2Section.tsx
  src/components/Purpose/PurposeRecommendedProductSection.tsx
  src/components/Purpose/ShareLinkPopup.tsx
  src/hooks/useMediaQuery.ts
  src/pages/MainProductDetailPage.tsx
  src/pages/purpose/ObjectPage.tsx
  src/pages/purpose/PurposeIngredientProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: ✨ Feature

#64 Feat/purpose UI yulmooop
  fetchApiData.mjs
  pnpm-lock.yaml
  src/App.tsx
  src/components/Purpose/MobileMainDetailPage.tsx
Labels: ✨ Feature

#65 feat: 알림 설정 API 연결
  src/apis/notification.ts
  src/assets/Profile2.svg
  src/pages/MyPage.tsx
  src/pages/NotificationSettingsPage.tsx
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#69 feat: 소셜 로그인 (WIP)
  src/App.tsx
  src/components/Auth/SocialLogin.tsx
  src/components/MainSearchBar.tsx
  src/components/Purpose/P3DMainDetailPage.tsx
  src/hooks/useLogout.ts
  src/pages/MainProductDetailPage.tsx
  src/pages/MyPage.tsx
  src/pages/alarm/AddOptionsModal.tsx
  src/pages/alarm/AlarmAddModal.tsx
  src/pages/alarm/DesktopAlarmAddToSearchPage.tsx
  src/pages/alarm/DesktopAlarmSettingsPage.tsx
  src/pages/alarm/MobileAlarmSettingsPage.tsx
  src/pages/alarm/TimePickerModal.tsx
  src/pages/auth/OauthRedirect.tsx
  src/pages/auth/SocialCallback.tsx
  src/pages/auth/SocialSignupForm.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: 📬 API

#70 인기영양제 페이지 추가
  src/App.tsx
  src/components/MainPage/ProductList.tsx
  src/components/Purpose/P2DSection.tsx
  src/components/Purpose/P2MDropdownPopup.tsx
  src/components/Purpose/P2Section.tsx
  src/components/Purpose/P3BrandSection.tsx
  src/components/Purpose/P3DMainDetailPage.tsx
  src/components/Purpose/P3IngredientTab.tsx
  src/components/Purpose/P3MMainDetailPage.tsx
  src/components/Purpose/P3TimingTab.tsx
  src/hooks/useIsMobile.ts
  src/pages/BestSupplement.tsx
  src/pages/auth/SocialCallback.tsx
  src/pages/purpose/ObjectPage.tsx
  src/pages/purpose/PurposeBrandProductsPage.tsx
  src/pages/purpose/PurposeIngredientProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: ✨ Feature

#73 feat: 소셜 로그인(WIP) 및 자체 로그인 모바일 버전 완성
  src/App.tsx
  src/apis/auth.ts
  src/layout/RootLayout.tsx
  src/pages/MyPage.tsx
  src/pages/alarm/DesktopAlarmAddPage.tsx
  src/pages/auth/DesktopEmailLoginPage.tsx
  src/pages/auth/DesktopEmailSignupDetailPage.tsx
  src/pages/auth/DesktopEmailSignupPage.tsx
  src/pages/auth/EmailLoginPage.tsx
  src/pages/auth/EmailSignupDetailPAge.tsx
  src/pages/auth/EmailSignupPage.tsx
  src/pages/auth/MobileEmailLoginPage.tsx
  src/pages/auth/MobileEmailSignupDetailPage.tsx
  src/pages/auth/MobileEmailSignupPage.tsx
  src/pages/auth/SocialSignupForm.tsx
  vite.config.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#74 feat: 약관 동의 추가
  public/images/search.png
  public/images/text.png
  src/App.tsx
  src/apis/auth.ts
  src/apis/terms.ts
  src/components/Footer.tsx
  src/components/MainPage/ProductList.tsx
  src/components/ingredient/IngredientSupplements.tsx
  src/components/terms/TermsAgreement.tsx
  src/components/terms/TermsList.tsx
  src/pages/MyPage.tsx
  src/pages/alarm/AlarmPage.tsx
  src/pages/alarm/DesktopAlarmAddPage.tsx
  src/pages/alarm/DesktopAlarmAddToSearchPage.tsx
  src/pages/alarm/DesktopAlarmEditPage.tsx
  src/pages/alarm/DesktopAlarmPage.tsx
  src/pages/alarm/DesktopAlarmSettingsPage.tsx
  src/pages/alarm/MobileAlarmPage.tsx
  src/pages/auth/DesktopEmailSignupPage.tsx
  src/pages/auth/SocialCallback.tsx
  src/pages/auth/SocialSignupForm.tsx
  src/pages/purpose/PurposeProductListPage.tsx
  src/types/alarm.ts
  src/types/ingredient.ts
  src/utils/alarm.ts
  tsconfig.app.json
  vite.config.ts
Labels: ✨ Feature, 📬 API

#78 목적별 영양제 조회 페이지 api 연동
  src/components/Purpose/LoginPromptModal.tsx
  src/components/Purpose/P2Section.tsx
  src/pages/MainProductDetailPage.tsx
  src/pages/purpose/PurposeIngredientProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: ✨ Feature

#79 feat: 이메일 회원가입 1·2단계 API 연동 및 임시 토큰 처리 추가
  src/apis/auth.ts
  src/components/ingredient/IngredientSupplements.tsx
  src/lib/axios.ts
  src/pages/SignInPage.tsx
  src/pages/alarm/DesktopAlarmSettingsPage.tsx
  src/pages/auth/DesktopEmailSignupDetailPage.tsx
  src/pages/auth/DesktopEmailSignupPage.tsx
  src/pages/auth/SocialCallback.tsx
  src/utils/signup.ts
  src/utils/terms.ts
Labels: ✨ Feature, ⚙ Setting, 📬 API

#81 feat: ingredient page api 연결
  src/apis/ingredient.ts
  src/components/ingredient/IngredientAlternatives.tsx
  src/components/ingredient/IngredientInfo.tsx
  src/components/ingredient/IngredientSearchSection.tsx
  src/components/ingredient/IngredientSupplements.tsx
  src/pages/IngredientPage.tsx
  src/pages/auth/SocialCallback.tsx
  src/pages/ingredients/IngredientDetailPage.tsx
  src/types/ingredient.ts
Labels: 📬 API

#82 인기영양제 api 수정 및 목적별 페이지 섭취 시기 수정
  src/components/Purpose/P2DSection.tsx
  src/components/Purpose/P2Section.tsx
  src/components/Purpose/P3DMainDetailPage.tsx
  src/components/Purpose/P3IngredientTab.tsx
  src/components/Purpose/P3MMainDetailPage.tsx
  src/components/Purpose/P3TimingTab.tsx
  src/pages/BestSupplement.tsx
  src/pages/MainProductDetailPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: ✨ Feature

#84 chore: add CI/CD (S3+CloudFront) deploy workflow
  .github/workflows/deploy.yml
Labels: 🚀 Deploy

#85 fix: deploy setting
  .github/workflows/deploy.yml
  src/lib/axios.ts
Labels: 🐛 BugFix, 🚀 Deploy

#86 fix: deploy.yml
  .github/workflows/deploy.yml
Labels: 🐛 BugFix, 🚀 Deploy

#87 fix: deploy setting
  .github/workflows/deploy.yml
Labels: 🐛 BugFix, 🚀 Deploy

#89 ui 크기 수정 및 목적별 페이지 api 연동 구조 수정
  src/components/Purpose/P3DMainDetailPage.tsx
  src/components/Purpose/P3MMainDetailPage.tsx
  src/pages/BestSupplement.tsx
  src/pages/purpose/ObjectPage.tsx
  src/pages/purpose/PurposeIngredientProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: ✨ Feature

#91 fix: deploy setting
  .github/workflows/deploy.yml
  src/App.tsx
Labels: 🐛 BugFix, 📬 API

#92 fix: deploy setting space
  .github/workflows/deploy.yml
Labels: 🐛 BugFix, 📬 API

#94 feat: improve alarm settings with API integration and weekday formatting
  src/pages/alarm/AlarmAddModal.tsx
  src/pages/alarm/AlarmEditModal.tsx
  src/pages/alarm/DesktopAlarmAddToSearchPage.tsx
  src/pages/alarm/DesktopAlarmEditPage.tsx
  src/pages/alarm/DesktopAlarmPage.tsx
  src/pages/alarm/DesktopAlarmSettingsPage.tsx
  src/pages/alarm/MobileAlarmPage.tsx
  src/pages/alarm/MobileAlarmSettingsPage.tsx
  src/types/alarm.ts
  src/utils/alarm.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#96 feat: integrate toggle API with optimistic update
  src/pages/alarm/AlarmAddModal.tsx
  src/pages/alarm/AlarmEditModal.tsx
  src/pages/alarm/MobileAlarmSettingsPage.tsx
Labels: 📬 API

#103 feat: UI 수정
  src/components/combination/CombinationProductCard.tsx
  src/index.css
  src/pages/combination/AddCombinationPage.tsx
  src/pages/combination/CombinationPage.tsx
  src/pages/combination/CombinationResultPage.tsx
Labels: ✨ Feature, 🎨 Html&css

#106 fix: purpose
  src/pages/BestSupplement.tsx
  src/pages/purpose/ObjectPage.tsx
  src/pages/purpose/PurposeBrandProductsPage.tsx
  src/pages/purpose/PurposeIngredientProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: 🐛 BugFix, 📬 API

#111 api 연동
  src/components/Purpose/P2MSection.tsx
  src/components/Purpose/P2Section.tsx
  src/components/Purpose/P3BrandSection.tsx
  src/components/Purpose/P3DMainDetailPage.tsx
  src/components/Purpose/P3IngredientTab.tsx
  src/components/Purpose/P3MMainDetailPage.tsx
  src/components/Purpose/P3TimingTab.tsx
  src/pages/BestSupplement.tsx
  src/pages/MainProductDetailPage.tsx
  src/pages/purpose/PurposeIngredientProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: ✨ Feature, 📬 API

#115 fix: 모바일·PC 알람 설정 페이지 로그인 확인 로직 추가
  src/pages/alarm/DesktopAlarmSettingsPage.tsx
  src/pages/alarm/MobileAlarmSettingsPage.tsx
Labels: ✨ Feature

#117 fix: prevent overlap between % and completion text in DesktopAlarmPage
  src/pages/alarm/AlarmPage.tsx
  src/pages/alarm/AlarmSettingsPage.tsx
  src/pages/alarm/DesktopAlarmPage.tsx
  src/utils/alarm.ts
Labels: 🎨 Html&css

#122 feat: 성분 페이지 권장섭취량 그래프 로그인 전 후 수정
  src/apis/ingredient.ts
  src/components/ingredient/IngredientInfo.tsx
  src/pages/IngredientPage.tsx
  src/types/ingredient.ts
Labels: ✨ Feature, 📬 API

#123 fix(axios): remove duplicate interceptors to allow guest access on main
  src/lib/axios.ts
Labels: 📬 API

#124 feat: mypage terms pages-service
  src/pages/MyPage.tsx
Labels: ✨ Feature

#129 목적별제품 리스트 api 연동
  src/pages/purpose/PurposeIngredientProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: ✨ Feature, 📬 API

#131 브랜드 목적 페이지 api 연동
  src/components/Purpose/P2MSection.tsx
  src/pages/MainProductDetailPage.tsx
  src/pages/purpose/ObjectPage.tsx
  src/pages/purpose/PurposeBrandProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: ✨ Feature, 📬 API

#133 ingredient tab api 연동
  src/components/Purpose/P3IngredientTab.tsx
  src/components/Purpose/P3MMainDetailPage.tsx
Labels: ✨ Feature, 📬 API

#135 목적 페이지 api 연동 끝!!
  src/components/Purpose/LoginPromptModal.tsx
  src/components/Purpose/P2MSection.tsx
  src/components/Purpose/P3BrandSection.tsx
  src/components/Purpose/P3DMainDetailPage.tsx
  src/components/Purpose/P3IngredientTab.tsx
  src/components/Purpose/P3MMainDetailPage.tsx
  src/components/Purpose/P3TimingTab.tsx
  src/pages/MainProductDetailPage.tsx
  src/pages/purpose/PurposeBrandProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: ✨ Feature, 📬 API

#140 feat: OauthRedirect에 FCM 동기화 로직 보강(SW 등록/지원 체크)
  src/pages/auth/OauthRedirect.tsx
Labels: 📬 API

#146 fix: PWA 매니페스트 설정 수정 (start_url 및 scope 경로 정상화)
  manifest.json
  src/lib/firebase.ts
Labels: 🚀 Deploy

#151 feat: 조합 페이지 게이지바 수정
  src/pages/combination/AddCombinationPage.tsx
  src/pages/combination/CombinationResultPage.tsx
Labels: 🎨 Html&css

#160 feat: 알림 권한 배너 및 알림 켜기 버튼 추가
  src/lib/push.ts
  src/pages/alarm/AlarmPage.tsx
Labels: ✨ Feature, 📬 API

#165 찜기능 수정
  src/pages/MainProductDetailPage.tsx
Labels: ✨ Feature, 📬 API

#174 키 중복 문제 및 텍스트 겹침 문제 해결
  src/assets/detailpagepng/coupangpartners.png
  src/assets/detailpagepng/heart.png
  src/assets/detailpagepng/heartfill.png
  src/assets/detailpagepng/i.png
  src/assets/detailpagepng/share.png
  src/components/Purpose/P2DSection.tsx
  src/components/Purpose/P2MSection.tsx
  src/components/Purpose/P3BrandSection.tsx
  src/components/Purpose/P3DMainDetailPage.tsx
  src/components/Purpose/P3MMainDetailPage.tsx
  src/pages/purpose/ObjectPage.tsx
  src/pages/purpose/PurposeBrandProductsPage.tsx
  src/pages/purpose/PurposeIngredientProductsPage.tsx
  src/pages/purpose/PurposeProductListPage.tsx
Labels: 🐛 BugFix, ✨ Feature, 🎨 Html&css

#175 feat: 조합 UI 수정
  src/components/combination/CombinationProductCard.tsx
  src/pages/combination/AddCombinationPage.tsx
  src/pages/combination/CombinationPage.tsx
  src/pages/combination/CombinationResultPage.tsx
Labels: 🎨 Html&css

#180 iOS PWA Web Push 구독 디버그용 SettingPage 및 push-ios.ts 추가
  src/App.tsx
  src/lib/push-ios.ts
  src/pages/SettingsPage.tsx
Labels: ✅ Test, 📬 API

#192 test
  public/index.html
  src/assets/link/kakaolink.png
  src/assets/link/link.png
  src/components/Purpose/P3DMainDetailPage.tsx
  src/components/Purpose/P3MMainDetailPage.tsx
  src/components/Purpose/P3MShareLinkPopup.tsx
  src/types/kakao.d.ts
  tsconfig.json
Labels: ✨ Feature, 📬 API

#193 testt
  src/pages/ingredients/IngredientDetailPage.tsx
Labels: 🐛 BugFix

#204 카톡 이미지 연동 확인
  src/components/Purpose/P3MMainDetailPage.tsx
Labels: ✨ Feature, 🎨 Html&css

#219 feat(combination-result): 섭취알림 버튼 반응형 동작 추가 — 모바일은 모달, 데스크탑은 페이지 이동
  src/pages/combination/CombinationResultPage.tsx
Labels: 📬 API

#223 feat: 조합 페이지 카카오톡 연동하기
  .gitignore
  src/components/combination/ShareLinkPopup.tsx
  src/pages/combination/CombinationResultPage.tsx
Labels: 📬 API
