Repository VitaCheck/vitacheck-fe, pull requests merged in 2025-07, with the labels that each got.

#6 fix: App.tsx 파일명 대소문자 수정
  src/App.tsx
Labels: 🐛 BugFix

#8 [Feat] 공용 컴포넌트 생성
  index.html
  src/assets/Bell.svg
  src/assets/User.svg
  src/assets/logo.svg
  src/components/NavBar.tsx
  src/components/ProductCard.tsx
  src/components/SearchBar.tsx
  src/layout/RootLayout.tsx
Labels: 🎨 Html&css

#14 [Feat] 메인, 마이, 알림 페이지 UI
  src/App.tsx
  src/assets/BaseProfile.svg
  src/assets/ProfileCat.svg
  src/assets/Setting.svg
  src/assets/VitaCheckcharacter.svg
  src/assets/alarm.svg
  src/assets/combination.svg
  src/assets/ingredient.svg
  src/assets/object.svg
  src/components/MainPage/MainCard.tsx
  src/components/MainPage/MainTop.tsx
  src/components/MainPage/MobileMainCard.tsx
  src/components/MainPage/NavSection.tsx
  src/components/MainPage/ProductList.tsx
  src/components/MyPage/MenuItem.tsx
  src/components/ProductCard.tsx
  src/components/SettingPage/SettingRow.tsx
  src/layout/RootLayout.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/NotificationCenterPage.tsx
  src/pages/NotificationSettingsPage.tsx
Labels: 🎨 Html&css

#15 feat: 조합 결과 페이지 UI 구현 및 관련 컴포넌트 추가
  src/assets/CatWithPointer.png
  src/assets/cat-face.png
  src/assets/chick.png
  src/assets/sad-cat.png
  src/components/CombinationProductCard.tsx
  src/components/SelectedProductList.tsx
  src/components/SubNavBar.tsx
  src/pages/AddCombinationPage.tsx
  src/pages/CombinationPage.tsx
  src/pages/CombinationResultPage.tsx
Labels: ✨ Feature, 🎨 Html&css

#10 feat: 성분 페이지 UI 구현
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/NoResultCat.png
  src/assets/Vector.svg
  src/assets/back.svg
  src/assets/cat.png
  src/assets/login.svg
  src/components/ingredient/IngredientAlternatives.tsx
  src/components/ingredient/IngredientDetailHeaderMobile.tsx
  src/components/ingredient/IngredientInfo.tsx
  src/components/ingredient/IngredientSupplements.tsx
  src/components/ingredient/IngredientTabs.tsx
  src/components/ingredient/NoSearchResult.tsx
  src/pages/IngredientPage.tsx
  src/pages/ingredients/IngredientDetailPage.tsx
Labels: 🎨 Html&css

#17 feat: 섭취 알림 페이지, 섭취 알림 설정 페이지 UI 구현
  package.json
  pnpm-lock.yaml
  public/images/add.png
  src/App.tsx
  src/pages/alarm/AlarmAddModal.tsx
  src/pages/alarm/AlarmPage.tsx
  src/pages/alarm/AlarmSettingsPage.tsx
  src/types/react-ios-time-picker.d.ts
  tailwind.config.js
Labels: ✨ Feature, 🎨 Html&css

#18 feat: add pusrpose ui
  src/components/IngredientTab.tsx
  src/components/MainDetailPageBrandSection.tsx
  src/components/PurposeRecommendedProductSection.tsx
  src/components/TimingTab.tsx
  src/pages/MainProductDetailPage.tsx
  src/pages/PurposeCardListPage.tsx
  src/pages/PurposeIngredientProductsPage.tsx
  src/pages/PurposeProductListPage.tsx
Labels: ✨ Feature, 🎨 Html&css

#21 feat: AlarmPage 모바일, PC버전 분리
  package.json
  pnpm-lock.yaml
  src/layout/RootLayout.tsx
  src/pages/alarm/AlarmPage.tsx
  src/pages/alarm/DesktopAlarmPage.tsx
  src/pages/alarm/MobileAlarmPage.tsx
Labels: ✨ Feature, 🎨 Html&css

#26 fix/ 충돌 해결
  src/App.tsx
  src/pages/CombinationPage.tsx
  src/pages/CombinationResultPage.tsx
Labels: 🐛 BugFix

#29 [FEAT]: 스크랩 페이지 UI
  src/App.tsx
  src/assets/heart-filled.svg
  src/components/MyPage/EditProfileHeader.tsx
  src/components/Scrap/ScrapIngredientItem.tsx
  src/components/Scrap/ScrapIngredientList.tsx
  src/components/Scrap/ScrapItemCard.tsx
  src/components/Scrap/ScrapList.tsx
  src/components/Scrap/ScrapTabHeader.tsx
  src/layout/RootLayout.tsx
  src/pages/MyPage.tsx
  src/pages/NotificationCenterPage.tsx
  src/pages/ScarpPage.tsx
Labels: ✨ Feature, 🎨 Html&css

#34 Feat/alarm UI
  package.json
  pnpm-lock.yaml
  src/pages/alarm/AlarmAddPanel.tsx
  src/pages/alarm/AlarmSettingsPage.tsx
  src/pages/alarm/DesktopAlarmPage.tsx
  src/pages/alarm/DesktopAlarmSettingsPage.tsx
  src/pages/alarm/MobileAlarmPage.tsx
  src/pages/alarm/MobileAlarmSettingsPage.tsx
Labels: ✨ Feature, 🎨 Html&css

#46 Update README.md
  README.md
Labels: 📃 Docs

#48 feat: notification API 연동
  .env
  pnpm-lock.yaml
  public/images/check.svg
  src/App.tsx
  src/pages/alarm/AlarmAddModal.tsx
  src/pages/alarm/AlarmAddPanel.tsx
  src/pages/alarm/AlarmEditModal.tsx
  src/pages/alarm/AlarmSettingsPage.tsx
  src/pages/alarm/DesktopAlarmAddPage.tsx
  src/pages/alarm/DesktopAlarmEditPage.tsx
  src/pages/alarm/DesktopAlarmPage.tsx
  src/pages/alarm/DesktopAlarmSettingsPage.tsx
  src/pages/alarm/MobileAlarmPage.tsx
  src/pages/alarm/MobileAlarmSettingsPage.tsx
  src/pages/combination/CombinationPage.tsx
  src/pages/combination/CombinationResultPage.tsx
  src/utils/cloudinary.ts
Labels: ✨ Feature, 📬 API
